"""
ClaimGuard AI
Authentication Schemas
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import (
    BaseModel,
    EmailStr,
    Field,
)


# ============================================================
# ROLES
# ============================================================

UserRole = Literal[
    "ADMIN",
    "PROVIDER",
    "INVESTIGATOR",
]


# ============================================================
# ADMIN LOGIN REQUEST
# ============================================================

class AdminLoginRequest(BaseModel):
    """
    Admin login request.
    """

    role: Literal["ADMIN"]

    email: EmailStr

    password: str


# ============================================================
# PROVIDER LOGIN REQUEST
# ============================================================

class ProviderLoginRequest(BaseModel):
    """
    Provider login request.

    Provider uses:
    - Provider ID
    - Password generated by Admin
    """

    role: Literal["PROVIDER"]

    provider_id: str = Field(
        min_length=1,
        max_length=50,
    )

    password: str


# ============================================================
# INVESTIGATOR LOGIN REQUEST
# ============================================================

class InvestigatorLoginRequest(BaseModel):
    """
    Investigator login request.

    Investigator uses:
    - Email
    - Password generated by Admin
    """

    role: Literal["INVESTIGATOR"]

    email: EmailStr

    password: str


# ============================================================
# USER PROFILE
# ============================================================

class UserProfile(BaseModel):

    id: str

    email: Optional[str] = None

    provider_id: Optional[str] = None

    full_name: Optional[str] = None

    role: UserRole

    is_active: bool

    created_at: Optional[str] = None

    updated_at: Optional[str] = None


# ============================================================
# AUTH RESPONSE
# ============================================================

class AuthResponse(BaseModel):

    message: str

    access_token: Optional[str] = None

    refresh_token: Optional[str] = None

    token_type: str = "bearer"

    user: Optional[UserProfile] = None

class RefreshTokenRequest(BaseModel):
    refresh_token: str

# ============================================================
# EXPORTS
# ============================================================

__all__ = [
    "UserRole",
    "AdminLoginRequest",
    "ProviderLoginRequest",
    "InvestigatorLoginRequest",
    "UserProfile",
    "AuthResponse",
    "RefreshTokenRequest",
]