"""
ClaimGuard AI
Provider Schemas
"""

from __future__ import annotations

from pydantic import BaseModel, EmailStr, Field


# ============================================================
# PROVIDER REGISTRATION
# ============================================================

class ProviderRegistrationRequest(BaseModel):
    """
    Provider submits registration details.

    Password is NOT entered by the provider.
    It will be generated by the administrator
    after approval.
    """

    provider_id: str = Field(
        min_length=1,
        max_length=50,
    )

    provider_name: str = Field(
        min_length=1,
        max_length=200,
    )

    email: EmailStr

    hospital_address: str = Field(
        min_length=1,
        max_length=500,
    )


# ============================================================
# RESPONSE
# ============================================================

class ProviderRegistrationResponse(BaseModel):

    message: str

    provider_id: str

    status: str


__all__ = [
    "ProviderRegistrationRequest",
    "ProviderRegistrationResponse",
]